import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";



export const metadata = {
  title: "Captain Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={'antialiased'}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
